os: unstable
clone_folder: C:\projects\go\src\github.com\douglaswth\yolo-octo-wookie
environment:
  GOPATH: C:\projects\go
install:
- dir C:\cygwin\bin
- appveyor SetVariable -Name PATH -Value "%GOPATH%\bin;%PATH%;C:\cygwin\bin"
build_script:
- make
test_script:
- make test
