install:
#- cinst cyg-get -y
#- cyg-get make
#- cyg-get mingw64-x86_64-gcc-g++
- appveyor SetVariable -Name PATH -Value "%PATH%;C:\tools\cygwin\bin"
- set
cache:
- C:\tools\cygwin
build_script:
- set
- make
test_script:
- make test
