install:
- dir C:\Program Files\AppVeyor\BuildAgent
- appveyor
#- cinst cyg-get -y
#- cyg-get make
#- cyg-get mingw64-x86_64-gcc-g++
- set
- where appveyor RefreshEnv
- appveyor SetVariable -Name PATH -Value %PATH%;C:\tools\cygwin\bin
- set
- RefreshEnv
cache:
- C:\tools\cygwin
build_script:
- make
test_script:
- make test
