os: unstable
install:
- dir C:\
#- cinst cyg-get -y
#- cyg-get make
#- cyg-get mingw64-x86_64-gcc-g++
#- appveyor SetVariable -Name PATH -Value "%PATH%;C:\tools\cygwin\bin"
#- dir C:\tools\cygwin\bin
#cache:
#- C:\tools\cygwin
build_script:
- make
test_script:
- make test
