install:
- dir C:\
- cinst cyg-get -y
- RefreshEnv
- cyg-get make
- cyg-get mingw64-x86_64-gcc-g++
- set PATH=%PATH%;C:\tools\cygwin\bin
- set
cache:
- C:\tools\cygwin
build_script:
- set PATH=%PATH%;C:\tools\cygwin\bin
- set
- make
test_script:
- make test
