clone_folder: C:\projects\go\src\github.com\douglaswth\yolo-octo-wookie
environment:
  GOPATH: C:\projects\go
install:
- appveyor SetVariable -Name PATH -Value "%GOPATH%\bin;%PATH%"
build_script:
- mingw32-make
test_script:
- mingw32-make test
