install:
- cinst cyg-get -y
- RefreshEnv
- cyg-get make
- cyg-get mingw64-x86_64-gcc-g++
cache:
- C:\tools\cygwin
build_script:
- C:\tools\cygwin\bin\make
test_script:
- C:\tools\cygwin\bin\make test
