install:
- appveyor DownloadFile https://www.cygwin.com/setup-x86_64.exe
- setup-x86_64.exe --site http://mirrors.kernel.org/sourceware/cygwin/ --only-site --root C:\cygwin64 --quiet-mode --local-package-dir C:\cygwin64\packages --no-shortcuts --no-startmenu --no-desktop --packages make --packages mingw64-x86_64-gcc-g++
- appveyor SetVariable -Name PATH -Value "%PATH%;C:\cygwin64\bin"
cache:
- C:\cygwin64
build_script:
- dir /S C:\cygwin64
- dir
- make
test_script:
- make test
